version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tender_service_app
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      POSTGRES_CONN: "postgres://postgres:root@db:5432/tender-service"
      POSTGRES_JDBC_URL: "jdbc:postgresql://db:5432/tender-service"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: "tender-service"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - tender_network

  db:
    image: postgres:15
    container_name: tender_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tender-service
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - tender_network

volumes:
  db_data:

networks:
  tender_network:
