// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Tender Management API
 *
 * API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка).
 *
 * API version: 1.0
 */

package openapi

import (
	"fmt"
)

// BidDecision : Решение по предложению
type BidDecision string

// List of BidDecision
const (
	APPROVED BidDecision = "Approved"
	REJECTED BidDecision = "Rejected"
)

// AllowedBidDecisionEnumValues is all the allowed values of BidDecision enum
var AllowedBidDecisionEnumValues = []BidDecision{
	"Approved",
	"Rejected",
}

// validBidDecisionEnumValue provides a map of BidDecisions for fast verification of use input
var validBidDecisionEnumValues = map[BidDecision]struct{}{
	"Approved": {},
	"Rejected": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BidDecision) IsValid() bool {
	_, ok := validBidDecisionEnumValues[v]
	return ok
}

// NewBidDecisionFromValue returns a pointer to a valid BidDecision
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBidDecisionFromValue(v string) (BidDecision, error) {
	ev := BidDecision(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for BidDecision: valid values are %v", v, AllowedBidDecisionEnumValues)
}

// AssertBidDecisionRequired checks if the required fields are not zero-ed
func AssertBidDecisionRequired(obj BidDecision) error {
	return nil
}

// AssertBidDecisionConstraints checks if the values respects the defined constraints
func AssertBidDecisionConstraints(obj BidDecision) error {
	return nil
}
