// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Tender Management API
 *
 * API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка).
 *
 * API version: 1.0
 */

package openapi

import (
	"errors"
	"fmt"
	"net/http"
)

var (
	// ErrTypeAssertionError is thrown when type an interface does not match the asserted type
	ErrTypeAssertionError = errors.New("unable to assert type")
)

// ParsingError indicates that an error has occurred when parsing request parameters
type ParsingError struct {
	Param string
	Err   error
}

func (e *ParsingError) Unwrap() error {
	return e.Err
}

func (e *ParsingError) Error() string {
	if e.Param == "" {
		return e.Err.Error()
	}

	return e.Param + ": " + e.Err.Error()
}

// RequiredError indicates that an error has occurred when parsing request parameters
type RequiredError struct {
	Field string
}

func (e *RequiredError) Error() string {
	return fmt.Sprintf("required field '%s' is zero value.", e.Field)
}

type ValidationError struct {
	Field string
}

func (e *ValidationError) Error() string {
	return e.Field
}

// ErrorHandler defines the required method for handling error. You may implement it and inject this into a controller if
// you would like errors to be handled differently from the DefaultErrorHandler
type ErrorHandler func(w http.ResponseWriter, r *http.Request, err error, result *ImplResponse)

// DefaultErrorHandler defines the default logic on how to handle errors from the controller. Any errors from parsing
// request params will return a StatusBadRequest. Otherwise, the error code originating from the servicer will be used.
func DefaultErrorHandler(w http.ResponseWriter, _ *http.Request, err error, result *ImplResponse) {
	var parsingErr *ParsingError
	if ok := errors.As(err, &parsingErr); ok {
		// Handle parsing errors
		_ = EncodeJSONResponse(err.Error(), func(i int) *int { return &i }(http.StatusBadRequest), w)
		return
	}

	var requiredErr *RequiredError
	if ok := errors.As(err, &requiredErr); ok {
		// Handle missing required errors
		_ = EncodeJSONResponse(err.Error(), func(i int) *int { return &i }(http.StatusUnprocessableEntity), w)
		return
	}

	var validErr *ValidationError
	if ok := errors.As(err, &validErr); ok {

		// Handle missing required errors
		_ = EncodeJSONResponse(err.Error(), func(i int) *int { return &i }(http.StatusBadRequest), w)
		return
	}

	if result.Code == http.StatusBadRequest {
		_ = EncodeJSONResponse(result.Body, func(i int) *int { return &i }(http.StatusBadRequest), w)
		return
	}

	if result.Code == http.StatusNotFound{
		_ = EncodeJSONResponse(result.Body, func(i int) *int { return &i }(http.StatusNotFound), w)
		return
	}
	_ = EncodeJSONResponse(err.Error(), func(i int) *int { return &i }(http.StatusInternalServerError), w)
	return

}


var (
	ErrNotFound      = errors.New("not found")
	ErrAlreadyExists = errors.New("already exists")
)

var (
	ErrSQLQuery       = errors.New("sql query error")
	ErrEmptyResultSet = errors.New("empty result set")
)

var (
	ErrNoUser             = errors.New("no user found")
	ErrUserNoRightsTender = errors.New("user does not have persmission for this tender")
	ErrUserNoRightsBid    = errors.New("user does not have persmission for this bid")
)

var (
	ErrNoOrganization    = errors.New("no organization found")
	ErrOrgNoRightsTender = errors.New("organization not belong to tender")
)
