// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Tender Management API
 *
 * API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка).
 *
 * API version: 1.0
 */

package openapi

import (
	"fmt"
)

// BidStatus : Статус предложения
type BidStatus string

// List of BidStatus
const (
	CREATED_BID   BidStatus = "Created"
	PUBLISHED_BID BidStatus = "Published"
	CANCELED_BID  BidStatus = "Canceled"
)

// AllowedBidStatusEnumValues is all the allowed values of BidStatus enum
var AllowedBidStatusEnumValues = []BidStatus{
	"Created",
	"Published",
	"Canceled",
}

// validBidStatusEnumValue provides a map of BidStatuss for fast verification of use input
var validBidStatusEnumValues = map[BidStatus]struct{}{
	"Created":   {},
	"Published": {},
	"Canceled":  {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BidStatus) IsValid() bool {
	_, ok := validBidStatusEnumValues[v]
	return ok
}

// NewBidStatusFromValue returns a pointer to a valid BidStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBidStatusFromValue(v string) (BidStatus, error) {
	ev := BidStatus(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for BidStatus: valid values are %v", v, AllowedBidStatusEnumValues)
}

// AssertBidStatusRequired checks if the required fields are not zero-ed
func AssertBidStatusRequired(obj BidStatus) error {
	return nil
}

// AssertBidStatusConstraints checks if the values respects the defined constraints
func AssertBidStatusConstraints(obj BidStatus) error {
	return nil
}
