// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Tender Management API
 *
 * API для управления тендерами и предложениями.   Основные функции API включают управление тендерами (создание, изменение, получение списка) и управление предложениями (создание, изменение, получение списка).
 *
 * API version: 1.0
 */

package openapi

type EditTenderRequest struct {

	// Полное название тендера
	Name string `json:"name,omitempty"`

	// Описание тендера
	Description string `json:"description,omitempty"`

	ServiceType TenderServiceType `json:"serviceType,omitempty"`
}

// AssertEditTenderRequestRequired checks if the required fields are not zero-ed
func AssertEditTenderRequestRequired(obj EditTenderRequest) error {
	return nil
}

// AssertEditTenderRequestConstraints checks if the values respects the defined constraints
func AssertEditTenderRequestConstraints(obj EditTenderRequest) error {
	return nil
}
